import React, { useState } from 'react';
import { motion } from 'motion/react';
import { Copy, Check, Download } from 'lucide-react';
import { ClickerConfig } from '../types';

interface ScriptExporterProps {
  config: ClickerConfig;
  theme: any;
}

export const ScriptExporter: React.FC<ScriptExporterProps> = ({ config, theme }) => {
  const [copied, setCopied] = useState(false);

  const generateScript = () => {
    const jitterCode = config.useCoordinates ? `
        jx = random.uniform(-${config.jitterX/2}, ${config.jitterX/2})
        jy = random.uniform(-${config.jitterY/2}, ${config.jitterY/2})` : '';

    const clickCall = config.clickType === 'double' 
      ? `pyautogui.doubleClick(${config.useCoordinates ? `${config.x} + jx, ${config.y} + jy` : ''})`
      : `pyautogui.click(${config.useCoordinates ? `${config.x} + jx, ${config.y} + jy` : ''}, button='${config.clickType}')`;

    const baseInterval = config.unit === 'ms' ? config.interval / 1000 : 
                        config.unit === 's' ? config.interval : 
                        config.unit === 'm' ? config.interval * 60 : 
                        60 / Math.max(1, config.interval);

    const minInterval = config.unit === 'ms' ? config.minInterval / 1000 : 
                       config.unit === 's' ? config.minInterval : 
                       config.unit === 'm' ? config.minInterval * 60 : 
                       60 / Math.max(1, config.minInterval);

    const maxInterval = config.unit === 'ms' ? config.maxInterval / 1000 : 
                       config.unit === 's' ? config.maxInterval : 
                       config.unit === 'm' ? config.maxInterval * 60 : 
                       60 / Math.max(1, config.maxInterval);

    const sleepCall = config.randomize
      ? `time.sleep(random.uniform(${minInterval}, ${maxInterval}))`
      : `time.sleep(${baseInterval})`;

    const loopType = config.useLimit ? `for _ in range(${config.repeatCount}):` : 'while True:';
    const durationCheck = config.useDuration ? `
    start_time = time.time()
    def check_duration():
        return (time.time() - start_time) < ${config.duration}` : 'def check_duration(): return True';

    return `import pyautogui
import time
import random

# Auto Clicker Script generated by Clicker Pro
# Mode: ${config.randomize ? 'Randomized' : 'Fixed'}
# Speed: ${config.unit === 'cpm' ? `${config.interval} Clicks Per Minute` : `${config.interval}${config.unit}`}
# Limit: ${config.useLimit ? `${config.repeatCount} clicks` : 'None'}
# Duration: ${config.useDuration ? `${config.duration}s` : 'None'}
# Coordinates: ${config.useCoordinates ? `(${config.x}, ${config.y})` : 'Current Mouse Position'}

print("Starting in ${config.startDelay} seconds... Switch to your target window.")
time.sleep(${config.startDelay})

${durationCheck}

try:
    ${config.useDuration ? 'while check_duration():' : loopType}
        ${jitterCode}
        ${clickCall}
        ${sleepCall}
except KeyboardInterrupt:
    print("Stopped.")`;
  };

  const copyToClipboard = () => {
    navigator.clipboard.writeText(generateScript());
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const downloadScript = () => {
    const blob = new Blob([generateScript()], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'clicker_pro_script.py';
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <motion.div
      key="scripts"
      initial={{ opacity: 0, x: 20 }}
      animate={{ opacity: 1, x: 0 }}
      exit={{ opacity: 0, x: -20 }}
      className="space-y-6"
    >
      <div className="flex items-center justify-between">
        <h2 className={`text-2xl font-bold tracking-tight ${theme.text}`}>Script Exporter</h2>
        <div className="flex gap-3">
          <button 
            onClick={downloadScript}
            className={`p-2.5 border ${theme.border} ${theme.radius || 'rounded-none'} ${theme.muted} hover:text-indigo-600 transition-colors`}
            title="Download Script"
          >
            <Download className="w-5 h-5" />
          </button>
          <button 
            onClick={copyToClipboard}
            className={`flex items-center gap-2 px-6 py-2.5 border ${theme.border} ${theme.radius || 'rounded-none'} ${theme.accent} text-xs font-bold uppercase tracking-wider hover:opacity-90 transition-all shadow-sm`}
          >
            {copied ? <Check className="w-4 h-4" /> : <Copy className="w-4 h-4" />}
            {copied ? 'Copied' : 'Copy Script'}
          </button>
        </div>
      </div>

      <div className={`relative ${theme.bg} border ${theme.border} ${theme.radius || 'rounded-none'} p-6 overflow-x-auto ${theme.card} ${theme.glow}`}>
        <pre className={`text-xs leading-relaxed ${theme.muted} ${theme.font || 'font-mono'}`}>
          {generateScript()}
        </pre>
      </div>

      <div className={`p-5 border-l-4 border-indigo-500/30 ${theme.card} ${theme.radius || 'rounded-none'} text-xs ${theme.muted} leading-relaxed`}>
        <span className={`${theme.text} font-bold block mb-2 uppercase tracking-widest text-[10px]`}>Deployment Notice</span>
        Requires Python 3.x and the <code className="bg-slate-100 px-1.5 py-0.5 rounded text-indigo-600">pyautogui</code> library. Install via: <br />
        <code className="text-indigo-500 mt-2 block font-bold">pip install pyautogui</code>
      </div>
    </motion.div>
  );
};
