import React, { useState } from 'react';
import { motion } from 'motion/react';
import { Copy, Check, Download } from 'lucide-react';
import { ClickerConfig } from '../types';

interface ScriptExporterProps {
  config: ClickerConfig;
  theme: any;
}

export const ScriptExporter: React.FC<ScriptExporterProps> = ({ config, theme }) => {
  const [copied, setCopied] = useState(false);

  const generateScript = () => {
    const clickCall = config.clickType === 'double' 
      ? `pyautogui.doubleClick(${config.useCoordinates ? `${config.x}, ${config.y}` : ''})`
      : `pyautogui.click(${config.useCoordinates ? `${config.x}, ${config.y}` : ''}, button='${config.clickType}')`;

    const baseInterval = config.unit === 'ms' ? config.interval / 1000 : 
                        config.unit === 's' ? config.interval : 
                        config.unit === 'm' ? config.interval * 60 : 
                        60 / Math.max(1, config.interval);

    const minInterval = config.unit === 'ms' ? config.minInterval / 1000 : 
                       config.unit === 's' ? config.minInterval : 
                       config.unit === 'm' ? config.minInterval * 60 : 
                       60 / Math.max(1, config.minInterval);

    const maxInterval = config.unit === 'ms' ? config.maxInterval / 1000 : 
                       config.unit === 's' ? config.maxInterval : 
                       config.unit === 'm' ? config.maxInterval * 60 : 
                       60 / Math.max(1, config.maxInterval);

    const sleepCall = config.randomize
      ? `time.sleep(random.uniform(${minInterval}, ${maxInterval}))`
      : `time.sleep(${baseInterval})`;

    const loopType = config.useLimit ? `for _ in range(${config.repeatCount}):` : 'while True:';
    const durationCheck = config.useDuration ? `
    start_time = time.time()
    def check_duration():
        return (time.time() - start_time) < ${config.duration}` : 'def check_duration(): return True';

    return `import pyautogui
import time
import random

# Auto Clicker Script generated by Clicker Pro
# Mode: ${config.randomize ? 'Randomized' : 'Fixed'}
# Speed: ${config.unit === 'cpm' ? `${config.interval} Clicks Per Minute` : `${config.interval}${config.unit}`}
# Limit: ${config.useLimit ? `${config.repeatCount} clicks` : 'None'}
# Duration: ${config.useDuration ? `${config.duration}s` : 'None'}
# Coordinates: ${config.useCoordinates ? `(${config.x}, ${config.y})` : 'Current Mouse Position'}

print("Starting in ${config.startDelay} seconds... Switch to your target window.")
time.sleep(${config.startDelay})

${durationCheck}

try:
    ${config.useDuration ? 'while check_duration():' : loopType}
        ${clickCall}
        ${sleepCall}
except KeyboardInterrupt:
    print("Stopped.")`;
  };

  const copyToClipboard = () => {
    navigator.clipboard.writeText(generateScript());
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const downloadScript = () => {
    const blob = new Blob([generateScript()], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'clicker_pro_script.py';
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <motion.div
      key="scripts"
      initial={{ opacity: 0, x: 20 }}
      animate={{ opacity: 1, x: 0 }}
      exit={{ opacity: 0, x: -20 }}
      className="space-y-6"
    >
      <div className="flex items-center justify-between">
        <h2 className="text-xl font-bold uppercase italic tracking-tight">Script Exporter</h2>
        <div className="flex gap-2">
          <button 
            onClick={downloadScript}
            className={`p-2 border ${theme.border} ${theme.muted} hover:text-white transition-colors`}
          >
            <Download className="w-4 h-4" />
          </button>
          <button 
            onClick={copyToClipboard}
            className={`flex items-center gap-2 px-4 py-2 border ${theme.border} ${theme.accent} text-[10px] font-bold uppercase hover:bg-white/5 transition-all`}
          >
            {copied ? <Check className="w-4 h-4" /> : <Copy className="w-4 h-4" />}
            {copied ? 'COPIED' : 'COPY_TO_CLIPBOARD'}
          </button>
        </div>
      </div>

      <div className={`relative ${theme.bg} border ${theme.border} p-6 overflow-x-auto`}>
        <pre className={`text-[11px] leading-relaxed ${theme.muted} ${theme.mono}`}>
          {generateScript()}
        </pre>
      </div>

      <div className={`p-4 border-l-2 border-[#00FF41]/30 bg-white/5 text-[10px] ${theme.muted} leading-relaxed`}>
        <span className="text-white font-bold block mb-1">DEPLOYMENT_NOTICE:</span>
        Requires Python 3.x and the `pyautogui` library. Install via: <br />
        <code className="text-[#00FF41] mt-1 block">pip install pyautogui</code>
      </div>
    </motion.div>
  );
};
