export const THEMES = {
  MATRIX: {
    name: 'MATRIX_OVERRIDE',
    bg: 'bg-[#050505]',
    card: 'bg-[#0A0A0B]',
    accent: 'text-[#00FF41]',
    accentBg: 'bg-[#00FF41]',
    border: 'border-[#1A1A1A]',
    text: 'text-[#E0E0E0]',
    muted: 'text-[#555555]',
    glow: 'shadow-[0_0_15px_rgba(0,255,65,0.1)]',
    radius: 'rounded-none',
    font: 'font-mono',
  },
  CYBERPUNK: {
    name: 'NEON_DISTRICT',
    bg: 'bg-[#0D0221]',
    card: 'bg-[#1A0831]',
    accent: 'text-[#FF00FF]',
    accentBg: 'bg-[#FF00FF]',
    border: 'border-[#3D1A5A]',
    text: 'text-[#E0E0E0]',
    muted: 'text-[#8A2BE2]',
    glow: 'shadow-[0_0_15px_rgba(255,0,255,0.1)]',
    radius: 'rounded-none',
    font: 'font-mono',
  },
  TERMINAL: {
    name: 'CLASSIC_SHELL',
    bg: 'bg-[#1E1E1E]',
    card: 'bg-[#252526]',
    accent: 'text-[#D4D4D4]',
    accentBg: 'bg-[#D4D4D4]',
    border: 'border-[#333333]',
    text: 'text-[#D4D4D4]',
    muted: 'text-[#808080]',
    glow: 'shadow-none',
    radius: 'rounded-none',
    font: 'font-mono',
  },
  MODERN: {
    name: 'Modern Utility',
    bg: 'bg-slate-50',
    card: 'bg-white',
    accent: 'text-indigo-600',
    accentBg: 'bg-indigo-600',
    border: 'border-slate-200',
    text: 'text-slate-900',
    muted: 'text-slate-500',
    glow: 'shadow-sm',
    radius: 'rounded-xl',
    font: 'font-sans',
  }
};

export const DEFAULT_CONFIG = {
  interval: 100,
  unit: 'ms' as const,
  clickType: 'left' as const,
  repeatCount: 100,
  useLimit: false,
  useDuration: false,
  duration: 60,
  startDelay: 3,
  randomize: false,
  minInterval: 50,
  maxInterval: 150,
  useCoordinates: false,
  x: 0,
  y: 0,
  jitterX: 0,
  jitterY: 0,
  soundEnabled: true,
  rippleEnabled: true,
  hotkeys: {
    start: 'F6',
    stop: 'F7',
    reset: 'F8',
  },
};
